<a href="https://colab.research.google.com/github/Polina-Stoyanova/Spectrum-Of-An-Amplitude-Modulated-Signal/blob/main/Aufgabe2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aufgabe 2:
#Modellieren Sie die Hardware-Implementierung eines CRC-Algorithmus mit standarten Bluetooth Polynom (oder einem anderen Standartpolynom mit r => 8). Zeigen Sie wie die Fehlererkennung funktioniert.

Lösung:

r = Order of the generator polynom G(x)


Bluetooth Polynom (CRC-CCITT) is a type of a Generator Polynom: x^16 + x^12 + x^5 + 1

x^16 + x^12 + x^5 + 1 => 10001000000100001

# IMPLEMENTIERUNG:

In [ ]:
import numpy as np

XOR Definition:

In [ ]:
def xor(a,b):
  if a == b:
    resultat = 0 
  else:
    resultat = 1 
  return resultat


Suche nach Rest (Remainder):

In [ ]:
def suche_rest(speicher_zellen, nachricht):
  XOR_x4 = 0
  XOR_x11 = 0
  XOR_x16 = 0

  for t in range(0, len(speicher_zellen), 1):
    speicher_zellen[t]=0



  for i in range(0, len(nachricht), 1):

    for j in range(0, len(speicher_zellen), 1):
        
      if (j == 15):
        speicher_zellen[j] = xor(nachricht[i], XOR_x16)
      elif (j == 10):
        speicher_zellen[j] = xor(speicher_zellen[j+1], XOR_x11)
      elif (j == 3):
        speicher_zellen[j] = xor(speicher_zellen[j+1], XOR_x4)      
      else:
        speicher_zellen[j] =  speicher_zellen[j+1]

    if (speicher_zellen[0] == 0):
      XOR_x4 = 0
      XOR_x11 = 0
      XOR_x16 = 0

    elif (speicher_zellen[0] == 1):
      XOR_x4 = 1
      XOR_x11 = 1
      XOR_x16 = 1

    print(speicher_zellen)
  return speicher_zellen


Prüfung, ob die Zahl eine Binarzahl ist:

In [ ]:
def check(string) :
  b = set(string)
  s = {0, 1}
  
  if s == b or b == {0} or b == {1}:
    print("Binary Number")
    bin = 1
  else :
    print("Non Binary Number")
    bin = 0
  return bin

Wahl der Nachricht:

In [ ]:
import numpy as np

user_input = [int(i) for i in input() if i.isdigit()]
print(user_input)

nachricht = np.array(user_input)
print(nachricht)

p = check(user_input)

while(p==0):
  user_input = [int(i) for i in input() if i.isdigit()]
  print(user_input)
  p = check(user_input)

In [ ]:
#Standard Bluetooth Polynom => 16 Speicherzellen
#Schaffen von Speicherzellen
speicher_zellen = np.array([0 for i in range(16)]) 

print("Leere Speicherzellen: ", speicher_zellen)
print("Speicherzellen Länge: ", len(speicher_zellen))

print("Nachricht: ", nachricht)
print("Nachricht Länge: ", len(nachricht))

#Das CRC-16 Polynom hat 16-bits Länge und deshalb soll die originale Nachricht mit 16 Nullen ergänzt werden

# Ergänzung der Nachricht 
ergänzt_nachricht = np.array([0 for i in range(16+len(nachricht))])
print("Länge der ergänten Nachricht: ", len(ergänzt_nachricht))

for i in range(0, len(nachricht), 1):
  ergänzt_nachricht[i] = nachricht[i]
print(ergänzt_nachricht)


Leere Speicherzellen:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Speicherzellen Länge:  16
Nachricht:  [1 0 1 0]
Nachricht Länge:  4
Länge der ergänten Nachricht:  20
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


Rest (Remainder) berechnen:

In [ ]:
rest = suche_rest(speicher_zellen, ergänzt_nachricht)
print("Rest: ", rest)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1]
[1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0]
[0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1]
[1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0]
Rest:  [1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0]


Kodierte Nachricht:

In [ ]:
kod_nachricht = np.concatenate((nachricht, rest))
print("Kodierte Nachricht: ", kod_nachricht)

Kodierte Nachricht:  [1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0]


Prüfung auf Fehler beim Senden des Nachrichts:

In [ ]:
prüf_zellen = np.array([0 for i in range(16)]) 
prüf = suche_rest(prüf_zellen, kod_nachricht)

print("Fehler beim Senden: ", prüf)
m=0

for i in range(0, len(prüf)):
  if(prüf[i] != 0):
    m+=1
if(m!=0):
  print("Es gibt einen Fehler beim Senden!")
else:
  print("Es gibt keinen Fehler beim Senden!")

Fehler beim Senden:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Es gibt keinen Fehler beim Senden!
